
tcp.port = 12345
udp.port = 12346

thread.keepalive.seconds = 60
thread.queue.capacity = 200

game.duration.minutes = 5

users.dir = ./data/persistent/users
games.dir = ./data/persistent/games

puzzle.data.file = ./data/Connections_Data.json

# How often (seconds) to flush the in-memory user cache to disk
persistence.interval.seconds=30